spring.application.name=ActividadSpringMVC
server.port=8080 

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Pubs;trustServerCertificate=true 
spring.datasource.username=sa 
spring.datasource.password=tiger 
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver 
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql = true 
spring.jpa.hibernate.ddl-auto=update 

spring.mvc.view.prefix=/WEB-INF/views/ 
spring.mvc.view.suffix=.jsp